remote_theme: hexops/whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

permalink: /:year/:title
paginate_path: /posts/:num
paginate: 5

title: Hexops' devlog
description: Hexops' developer log
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
twitter_image: https://raw.githubusercontent.com/hexops/website/master/media/png/square_logo.png
facebook_image: https://raw.githubusercontent.com/hexops/website/master/media/png/square_logo.png
