remote_theme: hexops/whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:title
paginate_path: /posts/:num
paginate: 5

title: Hexops devlog
description: Hexops' developer log
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name
    tag: /tags/:name
